- name: declaring a variable on the play level
  hosts: all
  become: yes
  connection: local
  vars:
    url: www.google.com
  tasks:
    - name: access variable
      ansible.builtin.debug:
          msg: url == {{url}}


- name: declaring a variable on the play level
  hosts: all
  become: yes
  connection: local
  tasks:
    - name: access variable
      ansible.builtin.debug:
          msg: url == {{url}}

      vars:
          url: www.google.com

- name: declaring a variable in another file
  hosts: all
  connection: local
  vars_files: 
         - var.yml
  tasks:
    - name: access a avariable
      ansible.builtin.debug:
        msg: url == {{url}}



